name: Test on PR
'on': pull_request

jobs:
  get_test_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.2.4
        name: Install PNPM Packager
      - name: Install Deps & Run Tests
        run: pnpm install --frozen-lockfile && pnpm run test:ci
      - name: Coverage Annotations
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
